In [212]:
import pandas as pd
import numpy as np

In [213]:
rng = np.random.RandomState()
Ser = pd.Series(rng.random(10))
print(Ser)

0    0.364663
1    0.224649
2    0.945982
3    0.980054
4    0.676532
5    0.565534
6    0.448009
7    0.382620
8    0.490172
9    0.528780
dtype: float64


In [214]:
print(id(rng))

2758039076936


In [215]:
type(Ser)

pandas.core.series.Series

In [216]:
df = pd.DataFrame(rng.randint(0,10,(4,4)),
                              columns=['A','B','C','D'])

In [217]:
df

A  B  C  D
0  0  1  5  3
1  6  5  8  8
2  4  8  6  7
3  5  6  6  4

In [218]:
df.mean(axis=0)

A    3.75
B    5.00
C    6.25
D    5.50
dtype: float64

In [219]:
df.mean(1)

0    2.25
1    6.75
2    6.25
3    5.25
dtype: float64

In [220]:
df.median(axis='rows')

A    4.5
B    5.5
C    6.0
D    5.5
dtype: float64

In [221]:
np.exp(Ser)

0    1.440028
1    1.251884
2    2.575341
3    2.664600
4    1.967045
5    1.760388
6    1.565192
7    1.466120
8    1.632597
9    1.696861
dtype: float64

In [222]:
np.sin(df*np.pi/4)

A             B             C             D
0  0.000000e+00  7.071068e-01 -7.071068e-01  7.071068e-01
1 -1.000000e+00 -7.071068e-01 -2.449294e-16 -2.449294e-16
2  1.224647e-16 -2.449294e-16 -1.000000e+00 -7.071068e-01
3 -7.071068e-01 -1.000000e+00 -1.000000e+00  1.224647e-16

In [223]:
area = pd.Series({'Alaska':172333, 'Texas':659662, 'Carlifornia':423646}, name='area')
Population = pd.Series({'Carlifornia':45672, 'Texas':12345, 'Newyork':34567},name='Population')

In [224]:
area

Alaska         172333
Texas          659662
Carlifornia    423646
Name: area, dtype: int64

In [225]:
print(Population)

Carlifornia    45672
Texas          12345
Newyork        34567
Name: Population, dtype: int64


In [226]:
area/Population

Alaska               NaN
Carlifornia     9.275836
Newyork              NaN
Texas          53.435561
dtype: float64

In [227]:
area.index | Population.index

Index(['Alaska', 'Carlifornia', 'Newyork', 'Texas'], dtype='object')

In [228]:
A = pd.Series([2,4,6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A

0    2
1    4
2    6
dtype: int64

In [229]:
B

1    1
2    3
3    5
dtype: int64

In [230]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [231]:
A*B

0     NaN
1     4.0
2    18.0
3     NaN
dtype: float64

In [232]:
fill = np.mean(A).astype(int)

In [233]:
fill

4

In [234]:
A.add(B, fill_value=fill)

0    6.0
1    5.0
2    9.0
3    9.0
dtype: float64

In [235]:
A = pd.DataFrame(rng.randint(0,20,(3,5)),
                              columns=list('ABCDE'))

In [236]:
A

A   B   C   D   E
0   9   9  17  14   5
1  15  19   0   0  16
2  10  12   7   4  18

In [237]:
B = pd.DataFrame(rng.randint(0,10,(3,3)),
                              columns=list('BAC'))

In [238]:
B

B  A  C
0  0  5  5
1  7  7  3
2  4  2  8

In [239]:
A+B

A   B   C   D   E
0  14   9  22 NaN NaN
1  22  26   3 NaN NaN
2  12  16  15 NaN NaN

In [240]:
A*B

A    B   C   D   E
0   45    0  85 NaN NaN
1  105  133   0 NaN NaN
2   20   48  56 NaN NaN

In [241]:
Data = A.stack()

In [242]:
Data

0  A     9
   B     9
   C    17
   D    14
   E     5
1  A    15
   B    19
   C     0
   D     0
   E    16
2  A    10
   B    12
   C     7
   D     4
   E    18
dtype: int32

In [243]:
Data.sum()/len(Data)

10.333333333333334

In [244]:
A.add(B, fill_value=fill, axis=0)

A   B   C     D     E
0  14   9  22  18.0   9.0
1  22  26   3   4.0  20.0
2  12  16  15   8.0  22.0

In [245]:
fill = A.stack().mean()

In [246]:
fill

10.333333333333334

In [254]:
A = rng.randint(10, size=(3,4))

In [255]:
A

array([[8, 8, 3, 2],
       [1, 8, 5, 3],
       [5, 6, 8, 6]])

In [256]:
A[0]

array([8, 8, 3, 2])

In [257]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-7,  0,  2,  1],
       [-3, -2,  5,  4]])

In [258]:
df = pd.DataFrame(A, columns=list('QRST'))

In [259]:
df

Q  R  S  T
0  8  8  3  2
1  1  8  5  3
2  5  6  8  6

In [260]:
df['Q'][0]

8

In [261]:
df.iloc[0]

Q    8
R    8
S    3
T    2
Name: 0, dtype: int32

In [262]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -7  0  2  1
2 -3 -2  5  4

In [263]:
df['R']

0    8
1    8
2    6
Name: R, dtype: int32

In [181]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  4  0  0  0
1  6  0  2  1
2 -2  0 -5  0

In [264]:
df.subtract(df['R'], axis=1)

Q   R   S   T   0   1   2
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN

In [183]:
halfrow = df.iloc[1, ::2]

In [184]:
df

Q  R  S  T
0  7  3  3  3
1  6  0  2  1
2  5  7  2  7

In [185]:
df - halfrow

Q   R    S   T
0  1.0 NaN  1.0 NaN
1  0.0 NaN  0.0 NaN
2 -1.0 NaN  0.0 NaN

In [196]:
df['R'].add(B, fill_value=fill,axis=0)

0   1   2   A   B   C
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN

In [208]:
fill = df.stack().mean()

In [209]:
fill

3.958333333333334

In [210]:
df.subtract(df['R'], axis=0)

Q    R         S         T
0  3.166667  0.0 -0.833333 -0.833333
1  2.166667  0.0 -1.833333 -2.833333
2  1.166667  0.0 -1.833333  3.166667

In [265]:
df.add(B, fill_value=fill,axis=1)

A       B       C       Q       R       S       T
0  10.125   5.125  10.125  13.125  13.125   8.125   7.125
1  12.125  12.125   8.125   6.125  13.125  10.125   8.125
2   7.125   9.125  13.125  10.125  11.125  13.125  11.125

In [266]:
fill = df.stack().mean()

In [267]:
fill

5.25

In [271]:
df.subtract(df['R'], axis=1)

Q   R   S   T   0   1   2
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN