In [85]:
import pandas as pd
import numpy as np

In [138]:
rng = np.random.RandomState()
Ser = pd.Series(rng.random(10))
print(Ser)

0    0.405495
1    0.114902
2    0.328209
3    0.972032
4    0.553162
5    0.240686
6    0.253013
7    0.074714
8    0.542143
9    0.252159
dtype: float64


In [139]:
print(id(rng))

2758173853832


In [140]:
type(Ser)

pandas.core.series.Series

In [141]:
df = pd.DataFrame(rng.randint(0,10,(4,4)),
                              columns=['A','B','C','D'])

In [142]:
df

A  B  C  D
0  8  1  7  6
1  0  1  7  4
2  3  5  7  2
3  1  0  6  3

In [143]:
df.mean(axis=0)

A    3.00
B    1.75
C    6.75
D    3.75
dtype: float64

In [144]:
df.mean(1)

0    5.50
1    3.00
2    4.25
3    2.50
dtype: float64

In [145]:
df.median(axis='rows')

A    2.0
B    1.0
C    7.0
D    3.5
dtype: float64

In [146]:
np.exp(Ser)

0    1.500045
1    1.121763
2    1.388480
3    2.643310
4    1.738742
5    1.272121
6    1.287900
7    1.077576
8    1.719689
9    1.286801
dtype: float64

In [147]:
np.sin(df*np.pi/4)

A         B         C             D
0 -2.449294e-16  0.707107 -0.707107 -1.000000e+00
1  0.000000e+00  0.707107 -0.707107  1.224647e-16
2  7.071068e-01 -0.707107 -0.707107  1.000000e+00
3  7.071068e-01  0.000000 -1.000000  7.071068e-01

In [148]:
area = pd.Series({'Alaska':172333, 'Texas':659662, 'Carlifornia':423646}, name='area')
Population = pd.Series({'Carlifornia':45672, 'Texas':12345, 'Newyork':34567},name='Population')

In [149]:
area

Alaska         172333
Texas          659662
Carlifornia    423646
Name: area, dtype: int64

In [150]:
print(Population)

Carlifornia    45672
Texas          12345
Newyork        34567
Name: Population, dtype: int64


In [99]:
area/Population

Alaska               NaN
Carlifornia     9.275836
Newyork              NaN
Texas          53.435561
dtype: float64

In [151]:
area.index | Population.index

Index(['Alaska', 'Carlifornia', 'Newyork', 'Texas'], dtype='object')

In [152]:
A = pd.Series([2,4,6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A

0    2
1    4
2    6
dtype: int64

In [153]:
B

1    1
2    3
3    5
dtype: int64

In [154]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [155]:
A*B

0     NaN
1     4.0
2    18.0
3     NaN
dtype: float64

In [156]:
fill = np.mean(A).astype(int)

In [157]:
fill

4

In [158]:
A.add(B, fill_value=fill)

0    6.0
1    5.0
2    9.0
3    9.0
dtype: float64

In [159]:
A = pd.DataFrame(rng.randint(0,20,(3,5)),
                              columns=list('ABCDE'))

In [160]:
A

A   B   C   D   E
0   2   8  15   8  16
1  19  12  10  19   5
2  11   3  18   8   9

In [161]:
B = pd.DataFrame(rng.randint(0,10,(3,3)),
                              columns=list('BAC'))

In [162]:
B

B  A  C
0  9  4  3
1  1  4  4
2  7  5  0

In [163]:
A+B

A   B   C   D   E
0   6  17  18 NaN NaN
1  23  13  14 NaN NaN
2  16  10  18 NaN NaN

In [164]:
A*B

A   B   C   D   E
0   8  72  45 NaN NaN
1  76  12  40 NaN NaN
2  55  21   0 NaN NaN

In [165]:
Data = A.stack()

In [166]:
Data

0  A     2
   B     8
   C    15
   D     8
   E    16
1  A    19
   B    12
   C    10
   D    19
   E     5
2  A    11
   B     3
   C    18
   D     8
   E     9
dtype: int32

In [167]:
Data.sum()/len(Data)

10.866666666666667

In [168]:
A.add(B, fill_value=fill, axis=0)

A   B   C     D     E
0   6  17  18  12.0  20.0
1  23  13  14  23.0   9.0
2  16  10  18  12.0  13.0

In [169]:
fill = A.stack().mean()

In [170]:
fill

10.866666666666667

In [171]:
A = rng.randint(10, size=(3,4))

In [172]:
A

array([[7, 3, 3, 3],
       [6, 0, 2, 1],
       [5, 7, 2, 7]])

In [173]:
A[0]

array([7, 3, 3, 3])

In [174]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -3, -1, -2],
       [-2,  4, -1,  4]])

In [175]:
df = pd.DataFrame(A, columns=list('QRST'))

In [176]:
df

Q  R  S  T
0  7  3  3  3
1  6  0  2  1
2  5  7  2  7

In [177]:
df['Q'][0]

7

In [178]:
df.iloc[0]

Q    7
R    3
S    3
T    3
Name: 0, dtype: int32

In [179]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -3 -1 -2
2 -2  4 -1  4

In [190]:
df['R']

0    3
1    0
2    7
Name: R, dtype: int32

In [181]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  4  0  0  0
1  6  0  2  1
2 -2  0 -5  0

In [182]:
df.subtract(df['R'], axis=1)

Q   R   S   T   0   1   2
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN

In [183]:
halfrow = df.iloc[1, ::2]

In [184]:
df

Q  R  S  T
0  7  3  3  3
1  6  0  2  1
2  5  7  2  7

In [185]:
df - halfrow

Q   R    S   T
0  1.0 NaN  1.0 NaN
1  0.0 NaN  0.0 NaN
2 -1.0 NaN  0.0 NaN

In [196]:
df['R'].add(B, fill_value=fill,axis=0)

0   1   2   A   B   C
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN

In [208]:
fill = df.stack().mean()

In [209]:
fill

3.958333333333334

In [210]:
df.subtract(df['R'], axis=0)

Q    R         S         T
0  3.166667  0.0 -0.833333 -0.833333
1  2.166667  0.0 -1.833333 -2.833333
2  1.166667  0.0 -1.833333  3.166667